server:
  port: 8000
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: test
---
server:
  port: 8080
  error:
    path: /error
    include-stacktrace: always

